=== ivansalcole/ProyectoLema_IVAN-ALAIN/dtd/definirAlmacen.dtd
<!ELEMENT casaSubastas (categorias)>
<!ATTLIST casaSubastas nombre CDATA #REQUIRED>
<!ATTLIST casaSubastas pais CDATA #REQUIRED>
<!ELEMENT categorias (categoria+)>
<!ELEMENT categoria (lote+)>
<!ATTLIST categoria id ID #REQUIRED>
<!ATTLIST categoria nombre (Arte|VehÃ­culos|Joyas|Historia) #REQUIRED>
<!ELEMENT lote (nombre, descripcion, precioSalida, precioActual, imagen, url)>
<!ATTLIST lote id ID #REQUIRED>
<!ATTLIST lote estado (activo|cerrado) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precioSalida (#PCDATA)>
<!ATTLIST precioSalida moneda CDATA #FIXED "EUR">
<!ELEMENT precioActual (#PCDATA)>
<!ATTLIST precioActual moneda CDATA #FIXED "EUR">
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== ivansalcole/ProyectoLema_IVAN-ALAIN/xml/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casaSubastas SYSTEM "../dtd/definirAlmacen.dtd">
<?xml-model href="../xsd/schemaalmacen.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<?xml-stylesheet href="../xslt/categoriasActivas.xsl" type="text/xsl"?>
<casaSubastas nombre="AMSUB" pais="España">
    <categorias>
        <categoria id="C1" nombre="Arte">
            <lote id="L1" estado="activo">
                <nombre>Cuadro de Picasso</nombre>
                <descripcion>
                    Pintura original del periodo cubista
                </descripcion>
                <precioSalida moneda="EUR">50000</precioSalida>
                <precioActual moneda="EUR">72000</precioActual>
                <imagen>../imagenes/picasso.jpg</imagen>
                <url>https://historia-arte.com/obras/beso-picasso</url>
            </lote>
            <lote id="L2" estado="activo">
                <nombre>Escultura romana</nombre>
                <descripcion>
                    Escultura de mármol del siglo II
                </descripcion>
                <precioSalida moneda="EUR">30000</precioSalida>
                <precioActual moneda="EUR">45500</precioActual>
                <imagen>../imagenes/escultura_romana.jpg</imagen>
                <url>https://luisaugustopascual.wordpress.com/tag/miguel-angel/</url>
            </lote>
        </categoria>
        <categoria id="C2" nombre="Vehículos">
            <lote id="L3" estado="activo">
                <nombre>
                    Ferrari Testarossa
                </nombre>
                <descripcion>Modelo clásico de 1989</descripcion>
                <precioSalida moneda="EUR">90000</precioSalida>
                <precioActual moneda="EUR">120000</precioActual>
                <imagen>../imagenes/Ferrari_Testarossa.jpg</imagen>
                <url>https://www.ferrari.com/es-ES/auto/testarossa</url>
            </lote>
            <lote id="L4" estado="cerrado">
                <nombre>
                    Volkswagen Beetle 1965
                </nombre>
                <descripcion>Coche clásico restaurado</descripcion>
                <precioSalida moneda="EUR">15000</precioSalida>
                <precioActual moneda="EUR">28000</precioActual>
                <imagen>../imagenes/beetle.jpg</imagen>
                <url>https://www.motor16.com/galerias/imagenes-volkswagen-beetle-1966/volkswagen-beetle-1966-imagenes/</url>
            </lote>
            <lote id="L5" estado="cerrado">
                <nombre>Moto de Valentino Rossi</nombre>
                <descripcion>
                    Moto oficial de competición de Valentino Rossi, utilizada en el Campeonato Mundial de MotoGP. 
                    Incluye firma y detalles exclusivos del piloto.
                </descripcion>
                <precioSalida moneda="EUR">250000</precioSalida>
                <precioActual moneda="EUR">500000</precioActual>
                <imagen>../imagenes/valentino_rossi_moto.jpg</imagen>
                <url>https://www.motoplanete.es/yamaha/7626/YZR-M1-2019/contact.html</url>
            </lote>
        </categoria>
        <categoria id="C3" nombre="Joyas">
            <lote id="L6" estado="activo">
                <nombre>Anillo de diamantes</nombre>
                <descripcion>
                    Anillo de oro con diamantes
                </descripcion>
                <precioSalida moneda="EUR">8000</precioSalida>
                <precioActual moneda="EUR">13500</precioActual>
                <imagen>../imagenes/anillo.jpg</imagen>
                <url>https://www.thejewellershop.com/es/marcas/brilladia/anillos/brilladia-anillo-de-diamantes-en-oro-amarillo-grabable-bdr0004-gsl</url>
            </lote>
            <lote id="L7" estado="activo">
                <nombre>Reloj Rolex esmeralda</nombre>
                <descripcion>
                    Rolex Submariner original
                </descripcion>
                <precioSalida moneda="EUR">12000</precioSalida>
                <precioActual moneda="EUR">19500</precioActual>
                <imagen>../imagenes/rolex.jpg</imagen>
                <url>https://www.medusa.jewelry/es/products/rolex-submariner-40mm-hulk-iced-emerald</url>
            </lote>
            <lote id="L8" estado="cerrado">
                <nombre>Collar Tiffany Blue Book</nombre>
                <descripcion>
                    Collar exclusivo de la colección Tiffany Blue Book 2025, con diamantes talla brillante y zafiros azules. 
                    Considerado una de las piezas más icónicas de la alta joyería mundial.
                </descripcion>
                <precioSalida moneda="EUR">250000</precioSalida>
                <precioActual moneda="EUR">500000</precioActual>
                <imagen>../imagenes/tiffany_blue_book.jpg</imagen>
                <url>https://www.tiffany.es/?srsltid=AfmBOopwyl7le52e9HjkNWJ12CinMv5Fe898dFruJKiL-E00Qlkk2AnX</url>
            </lote>
            <lote id="L9" estado="activo">
                <nombre>Anillo de la Reina Elizabeth II</nombre>
                <descripcion>
                    Anillo histórico perteneciente a la colección privada de la Reina Elizabeth II, con diamante central de 5 quilates 
                    rodeado de piedras preciosas. Pieza única con certificado de autenticidad.
                </descripcion>
                <precioSalida moneda="EUR">750000</precioSalida>
                <precioActual moneda="EUR">24000000</precioActual>
                <imagen>../imagenes/Anillo_de_la_Reina_Elizabeth_II.jpg</imagen>
                <url>https://taylorandhart.com/eu/blog/queen-elizabeth-iis-art-deco-engagement-ring</url>
            </lote>
        </categoria>
        <categoria id="C4" nombre="Historia">
            <lote id="L10" estado="activo">
                <nombre>Sable Chino del Siglo XVIII</nombre>
                <descripcion>
                    ricamente incrustado con oro, plata y joyas, y la espada de presentación de Ulysses S. Grant
                </descripcion>
                <precioSalida moneda="EUR">2000000</precioSalida>
                <precioActual moneda="EUR">2700000</precioActual>
                <imagen>../imagenes/sablechino.jpg</imagen>
                <url>https://www.metmuseum.org/art/collection/search/26535</url>
            </lote>
            <lote id="L11" estado="cerrado">
                <nombre>Espada de Napoleon</nombre>
                <descripcion>
                    El arma, concebida para el uso personal del entonces Primer Cónsul, acompañó a Napoleón
                </descripcion>
                <precioSalida moneda="EUR">700000</precioSalida>
                <precioActual moneda="EUR">3700000</precioActual>
                <imagen>../imagenes/espadanapoleon.jpg</imagen>
                <url>https://www.abc.es/cultura/reaparece-espada-personal-napoleon-tras-200-anos-20250524174721-nt.html</url>
            </lote>
            <lote id="L12" estado="cerrado">
                <nombre>Mapa original del Descubrimiento de América</nombre>
                <descripcion>
                    Mapa del siglo XV que muestra rutas de exploración del descubrimiento de América. 
                    Manuscrito original con anotaciones de navegantes de la época, pieza de colección histórica.
                </descripcion>
                <precioSalida moneda="EUR">200000</precioSalida>
                <precioActual moneda="EUR">225000</precioActual>
                <imagen>../imagenes/mapa_descubrimiento_america.jpg</imagen>
                <url>https://es.wikipedia.org/wiki/Mapa_de_Juan_de_la_Cosa</url>
            </lote>
        </categoria>
    </categorias>
</casaSubastas>
